# Generated by Django 3.2.3 on 2021-06-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='States',
        ),
    ]
