# Generated by Django 3.2.3 on 2021-06-21 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poll_Description', models.TextField()),
                ('is_Active', models.BooleanField(default=True)),
                ('Publish_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Make_Visible', models.BooleanField(default=False)),
                ('Poll_State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.states')),
            ],
        ),
    ]
