# Generated by Django 3.2.3 on 2021-06-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Political_Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Party_Name', models.CharField(max_length=100)),
                ('Party_Symbol', models.ImageField(upload_to='')),
            ],
        ),
    ]
