# Generated by Django 3.2.3 on 2021-06-22 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_political_parties'),
    ]

    operations = [
        migrations.CreateModel(
            name='constituency_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consistituent_Name', models.CharField(max_length=50)),
                ('Consistituent_State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.states')),
            ],
        ),
    ]
