# Generated by Django 3.2.3 on 2021-06-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_constituency_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate_Name', models.CharField(max_length=255)),
                ('Party_PIC', models.ImageField(upload_to='')),
                ('Votes_Obtained', models.CharField(max_length=10)),
                ('Constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.constituency_table')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.political_parties')),
                ('Poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.poll')),
            ],
        ),
    ]
