# Generated by Django 3.2.3 on 2021-06-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_candidates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidates',
        ),
    ]
